# ' Generates the standard barplot of scores for each sample
# '
# ' This function takes the barplot data generated by organise.barplot.data
# ' and returns the barplot if no filename is specified. If filename is
# ' is specified it saves the plot as file and returns NULL.
# '
# ' @param barplot.data A dataframe with Columns Sum, of scores, and Sample
# ' @param filename A filename where to save plot. If NULL the barplot object will be returned
# ' @param cutoff A function to plot the cutoff fot what is deemed a poor sample
# ' @return the barplot or NULL depending if filename is specified
# ' @export
get.qc.barplot <- function(barplot.data, filename = NULL, cutoff = (function(x) {x <- -20})) {
    barplot <- BoutrosLab.plotting.general::create.barplot(
        filename = filename,
        Sum ~ Sample,
        barplot.data,
        # Formatting
        yaxis.cex = 0.8,
        xaxis.rot = 90,
        xaxis.cex = 0,
        yaxis.tck = 0,
        xaxis.tck = 0,
        xlab.label = "",
        ylab.label = "Sum of Z (Z < 0)",
        ylab.cex = 1,
        axes.lwd = 2,
        border.col = "black",
        # Lines
        line.func = cutoff,
        line.from = 0,
        line.to = 162,
        line.col = 'darkgrey'
        );
    }

# ' Generates the standard heatmap of scores for each sample
# '
# ' This function takes the the scores for each sample and each metric,
# ' after being sign-corrected, and returns the standard heatmap, if filename
# ' is NULL. If filename is not NULL it saves the heatmap to file and returns NULL
# '
# ' @param qc.data.heatmap A dataframe of sign-corrected scores for each Sample
# ' @param filename A filename to save heatmap. If NULL the heatmap object will be returned
# ' @return the heatmap or NULL depending if filename is specified
# ' @export
get.qc.heatmap <- function(qc.data.heatmap, ylabels) {
    heatmap <- BoutrosLab.plotting.general::create.heatmap(
        qc.data.heatmap,
        # Axes labels
        yaxis.lab = ylabels,
        yaxis.cex = 0.8,
        xaxis.rot = 90,
        xaxis.lab = colnames(df),
        xaxis.cex = 0, # 0.8,
        yaxis.tck = 0,
        xlab.cex = 1,
        xlab.label = "Samples",
        # Clustering
        clustering.method = "none",
        # Colour scheme
        colour.scheme = c("red", "white"),
        colour.centering.value = 0,
        colourkey.labels.at = c(-10:0),
        colourkey.cex = 1,
        at = seq(0, -10, -2),
        same.as.matrix = TRUE,
        # Grid Rows
        grid.row = TRUE,
        row.lines = 26.5 - c(6, 12, 18, 22, 24),
        row.colour = "grey",
        row.lwd = 1,
        axes.lwd = 2
        );
    }

# ' Generates the multipanel plot of heatmap and barplot
# '
# ' This function takes the barplot and heatmap and returns the multipanel plot
# ' of the two.
# '
# ' @param barplot A barplot of the samples aggregated score
# ' @param heatmap A heatmap of the sign-corrected scores for each sample
# ' @param filename A filename to save the multipanel plot
# ' @return NULL
# ' @export
get.qc.multipanelplot <- function(barplot, heatmap, filename) {
    BoutrosLab.plotting.general::create.multipanelplot(
        filename = filename,
        width = 10,
        height = 8,
        plot.objects = list(barplot, heatmap),
        layout.height = 2,
        layout.width = 1,
        plot.objects.heights = c(1, 3),
        y.spacing = -1,
        ylab.axis.padding = -19,
        left.padding = 8,
        main = "QC Summary",
        main.cex = 0,
        );
    }
